### ISSUE TITLE
Cleared screen when executing inside a Docker container

### ISSUE THREAD

**Issue by pbedia-stratio** [mlorenzo-stratio/vcli#16]
In version When executing a command using the new stdin processing, INSIDE a docker container, the screen is cleared and nothing is shown.

**Comment by ml0renz0** [comment]
Fixed in https://github.com/mlorenzo-stratio/vcli/commit/344e5fd495dbb29330db168a28d78df21d101d8d. Available in [0.4.5](https://github.com/mlorenzo-stratio/vcli/releases/tag/0.4.2)
