### ISSUE TITLE
Data for put command cannot contain spaces

### ISSUE THREAD

**Issue by grios-stratio** [mlorenzo-stratio/vcli#18]
When running the put command, if the json containing the data has some spaces, it is not parsed correctly and the put command returns a 400 status code. (Maybe this happens with other commands that submit new data?)

**Comment by ml0renz0** [comment]
Fixed in version [0.5.8](https://github.com/mlorenzo-stratio/vcli/releases/tag/0.5.8)

**Comment by mlorenzo-stratio** [comment]
[0.5.8](url)
