### ISSUE TITLE
Problems to delete certificates entries in path with dot

### ISSUE THREAD

**Issue by alopez-stratio** [mlorenzo-stratio/vcli#20]
If certificates has next path: /userland/certificates/postgresqa.frameworks1 and want to delete entry like pg-0007.postgresqa.frameworks1.mesos_crt, it's not possible to delete it.

**Comment by ml0renz0** [comment]
Problem was not pathname nor secret name nor secret key/values. Issue was due to curl argument list too long:
`./vcli: line 553: /usr/bin/curl: Argument list too long`
Fixed in [0.5.9](https://github.com/mlorenzo-stratio/vcli/releases/tag/0.5.9)
