### ISSUE TITLE
VAULT_ADDR support

### ISSUE THREAD

**Issue by jshuping** [mlorenzo-stratio/vcli#3]
Neat tool! Since VAULT_ADDR is the common setting, it would be nice for vcli to support/read it
instead of the  _HOST/_PORT vars.

**Comment by ml0renz0** [comment]
Thanks @jshuping. You're right vcli should support VAULT_ADDR environment variable and now, if it works for you too, does.
Fixed in 8c9d7a2e2797ce73ee3e79bde3387801f9a1835f
