### ISSUE TITLE
New Feature: Delete attribute inside a secret

### ISSUE THREAD

**Issue by abandin-stratio** [mlorenzo-stratio/vcli#6]
self-explanatory

Kisses Mudafacka

**Comment by ml0renz0** [comment]
You got it bro!
Fixed in [pull #8](https://github.com/mlorenzo-stratio/vcli/pull/8) and available along with stdin processing and enhanced commands help on the new release [0.4.0](https://github.com/mlorenzo-stratio/vcli/releases/tag/0.4.0)
